Reformat slack handle notification

diff --git a/src/orb.yml b/src/orb.yml
--- a/src/orb.yml
+++ b/src/orb.yml
@@ -81,32 +81,11 @@ commands:
                 type: boolean
         steps:
             - run:
-                command: |-
-                    #!/bin/bash
-                    set -eo pipefail
-                    function run_main() {
-                        USER_ALIAS=$(curl -s -H "Authorization: Bearer ${CODA_API_TOKEN}" \
-                        -G --data-urlencode "query=c-6ni4kHGNwE:\"${CIRCLE_USERNAME}\"" \
-                        'https://staging.coda.io/apis/v1/docs/s2i6oFeghW/tables/grid-QGyaiXZDwu/rows' \
-                        | jq '.items[0].values."c-26If9Zttyp"' | tr -d '"')
-                        if [ "$USER_ALIAS" != "null" ]; then
-                            USER_EMAIL=$([[ "${USER_ALIAS}" == *@* ]] && echo "$USER_ALIAS" || echo "${USER_ALIAS}@coda.io")
-                        else
-                            USER_EMAIL=""
-                        fi
-                        echo "$USER_EMAIL"
-                        echo "export USER_EMAIL=${USER_EMAIL}" >> $BASH_ENV
-
-                    }
-
-                    ORB_TEST_ENV="bats-core"
-                    if [ "${0#*$ORB_TEST_ENV}" == "$0" ]; then
-                        run_main
-                    fi
+                command: "#!/bin/bash\nset -eo pipefail\nCODA_CIRCLECI_USER_NAME_COL=\"c-6ni4kHGNwE\"\nCODA_CIRCLECI_USER_ALIAS_COL=\"c-26If9Zttyp\"\nUSER_EMAIL=\"\"\nfunction run_main() {\n    USER_ALIAS=$(curl -s -H \"Authorization: Bearer ${CODA_API_TOKEN}\" \\\n    -G --data-urlencode \"query=${CODA_CIRCLECI_USER_NAME_COL}:\\\"${CIRCLE_USERNAME}\\\"\" \\\n    'https://staging.coda.io/apis/v1/docs/s2i6oFeghW/tables/grid-QGyaiXZDwu/rows' \\\n    | jq --arg CODA_CIRCLECI_USER_ALIAS_COL \"$CODA_CIRCLECI_USER_ALIAS_COL\" '.items[0].values.\"$CODA_CIRCLECI_USER_ALIAS_COL\"' | tr -d '\"')\n    if [ \"$USER_ALIAS\" != \"null\" ]; then\n        USER_EMAIL=$([[ \"${USER_ALIAS}\" == *@* ]] && echo \"$USER_ALIAS\" || echo \"${USER_ALIAS}@coda.io\")\n    fi\n    echo \"$USER_EMAIL\"\n    echo \"export USER_EMAIL=${USER_EMAIL}\" >> \"$BASH_ENV\"\n    if [ ! -z \"$SLACK_BOT_TOKEN\" ]; then \n        SLACK_USER_ID=$(curl -s -H \"Authorization: Bearer $SLACK_BOT_TOKEN\" \\\n            https://slack.com/api/users.lookupByEmail?email=${USER_EMAIL} \\\n            | jq '.user.id' | tr -d '\"')\n        echo \"export SLACK_USER_ID=${SLACK_USER_ID}\" >> \"$BASH_ENV\"\n    fi\n}\n\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*$ORB_TEST_ENV}\" == \"$0\" ]; then\n    run_main\nfi"
                 name: Get User Email
                 when: always
             - run:
-                command: "#!/bin/bash\nCIRCLE_FETCH_PAGE_SIZE=100\nCIRCLE_FETCH_MAX_PAGES=100\nresponse=\"\"\n\nfunction get_recent_builds() {\n    offset=$(($1*CIRCLE_FETCH_PAGE_SIZE))\n    url=\"https://circleci.com/api/v1/project/${CIRCLE_PROJECT_USERNAME}/\\\n        ${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}?circle-token=\\\n        ${CIRCLE_LOCK_API_TOKEN}&limit=100&offset=${offset}&filter=successful\"\n    response=$(curl \"$url\" | jq '.')\n}\n\nfunction run_main() {\n    latest_build_num=0\n    latest_git_hash=\"\"\n    job_name=$CIRCLE_JOB\n    page=0\n    DIFF_URL=\"\"\n    # while latest hash still not found and pages gone through less than max page search\n    while [[ $latest_git_hash == \"\" ]] && [[ $page < $CIRCLE_FETCH_MAX_PAGES ]]\n    do\n        # get response json of the page and parse\n        get_recent_builds $page\n        for build in $(echo \"$response\" | jq -c '.[]')\n        do\n            if [[ $(echo \"$build\" | jq -r '.outcome') != \"success\" ]]; then\n                continue\n            fi\n            if [[ $(echo \"$build\" | grep 'workflows') == \"\" ]]; then \n                continue \n            fi \n            if (( $(echo \"$build\" | jq  -r '.build_num') > latest_build_num ))\\\n            && [[ $(echo \"$build\" | jq -r '.workflows.job_name') == \"$job_name\" ]]; then\n                latest_build_num=$(echo \"$build\" | jq -r '.build_num') \n                latest_git_hash=$(echo \"$build\" | jq -r '.vcs_revision')\n            fi\n        done\n        if [ -z \"$latest_git_hash\" ]; then\n            # if latest_git_hash is not empty then increase page and set\n            page=$((page+1))\n        fi\n    done\n    if [ -z \"$latest_git_hash\" ]; then\n        # if latest_git_hash is not empty then increase page and set\n        echo \"$latest_git_hash\"\n        DIFF_URL=\"https://github.com/kr-project/${CIRCLE_PROJECT_REPONAME}/compare/${latest_git_hash}...${CIRCLE_SHA1}\"\n    fi\n    #DIFF_URl is printed for bats test, exported for ci\n    echo \"$DIFF_URL\"\n    echo \"export DIFF_URL=$DIFF_URL\" >> $BASH_ENV\n\n}\n\n# Will not run if sourced for bats-core tests.\n# View src/tests for more information.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*$ORB_TEST_ENV}\" == \"$0\" ]; then\n    run_main\nfi\n"
+                command: "#!/bin/bash\nCIRCLE_FETCH_PAGE_SIZE=100\nCIRCLE_FETCH_MAX_PAGES=100\nresponse=\"\"\nfunction get_recent_builds() {\n    offset=$(($1*CIRCLE_FETCH_PAGE_SIZE))\n\n    url=\"https://circleci.com/api/v1/project/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}?circle-token=${CIRCLE_TOKEN}&limit=100&offset=${offset}&filter=successful\"\n\n    response=$(curl \"$url\" | jq '.')\n    response_code=$(curl -s -o /dev/null -w \"%{http_code}\" \"$url\")\n}\n\nfunction run_main() {\n    latest_build_num=0\n    latest_git_hash=\"\"\n    job_name=$CIRCLE_JOB\n    page=0\n    DIFF_URL=\"\"\n\n    # while latest hash still not found and pages gone through less than max page search\n    while [[ $latest_git_hash == \"\" ]] && [[ $page < $CIRCLE_FETCH_MAX_PAGES ]]\n    do\n        # get response json of the page and parse\n        get_recent_builds $page\n        if [[ $response_code != 200 ]]; then \n            echo \"Error: CircleCI page not found\"\n            exit 0\n        fi\n        for build in $(echo \"$response\" | jq -c '.[]')\n        do\n            if [[ $(echo \"$build\" | jq -r '.outcome') != \"success\" ]]; then\n                continue\n            fi\n            if [[ $(echo \"$build\" | grep 'workflows') == \"\" ]]; then \n                continue \n            fi \n            if (( $(echo \"$build\" | jq  -r '.build_num') > latest_build_num ))\\\n            && [[ $(echo \"$build\" | jq -r '.workflows.job_name') == \"$job_name\" ]]; then\n                latest_build_num=$(echo \"$build\" | jq -r '.build_num') \n                latest_git_hash=$(echo \"$build\" | jq -r '.vcs_revision')\n            fi\n        done\n        if [ -z \"$latest_git_hash\" ]; then\n            # if latest_git_hash is empty then increase page and keep looking\n            page=$((page+1))\n        fi\n    done\n    if [ ! -z \"$latest_git_hash\" ]; then\n        # if latest_git_hash was found set DIFF_URL\n        #DIFF_URl is printed for bats test, exported for ci\n        DIFF_URL=\"https://github.com/kr-project/${CIRCLE_PROJECT_REPONAME}/compare/${latest_git_hash}...${CIRCLE_SHA1}\"\n        echo \"export DIFF_URL=$DIFF_URL\" >> \"$BASH_ENV\"\n        echo \"$DIFF_URL\"\n    else\n        echo \"No last good commit hash for this branch\"\n    fi\n}\n\n# Will not run if sourced for bats-core tests.\n# View src/tests for more information.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*$ORB_TEST_ENV}\" == \"$0\" ]; then\n    run_main\nfi\n"
                 name: Get diff url
                 when: on_fail
             - run:
@@ -211,50 +190,48 @@ commands:
                 type: string
         steps:
             - run:
-                command: |-
-                    set -eo pipefail
-
-                    USER_ALIAS=$(curl -s -H "Authorization: Bearer << parameters.CODA_API_TOKEN >>" \
-                      -G --data-urlencode "query=<< parameters.CODA_CIRCLECI_USER_NAME_COL >>:\"${CIRCLE_USERNAME}\"" \
-                      '<< parameters.CODA_USER_ROSTER_TABLE_URL >>' \
-                      | jq '.items[0].values."<< parameters.CODA_CIRCLECI_USER_ALIAS_COL >>"' | tr -d '"')
-                    USER_EMAIL=$([[ "${USER_ALIAS}" == *@* ]] && echo "$USER_ALIAS" || echo "${USER_ALIAS}@<< parameters.EMAIL_DOMAIN >>")
-                    SLACK_USER_ID=$(curl -s -H "Authorization: Bearer << parameters.SLACK_BOT_TOKEN >>" \
-                      https://slack.com/api/users.lookupByEmail?email=${USER_EMAIL} \
-                      | jq '.user.id' | tr -d '"')
-
-                    curl -X POST -H "Authorization: Bearer << parameters.SLACK_BOT_TOKEN >>" \
-                      -H "Content-Type: application/json" -d \
-                      "{ \
-                        \"channel\": \"${SLACK_USER_ID}\", \
-                        \"attachments\": [ \
-                          { \
-                            \"text\": \"Pending Approval for ${CIRCLE_PROJECT_REPONAME} push (${CIRCLE_USERNAME})\", \
-                            \"fields\": [ \
-                              { \
-                                \"title\": \"Project\", \
-                                \"value\": \"${CIRCLE_PROJECT_REPONAME}\", \
-                                \"short\": true \
-                              }, \
-                              { \
-                                \"title\": \"Job Number\", \
-                                \"value\": \"${CIRCLE_BUILD_NUM}\", \
-                                \"short\": true \
-                              } \
-                            ], \
-                            \"actions\": [ \
-                              { \
-                                \"type\": \"button\", \
-                                \"text\": \"Visit Workflow\", \
-                                \"url\": \"https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\" \
-                              } \
-                            ], \
-                            \"color\": \"#f46a54\" \
-                          } \
-                        ] \
-                      }" \
-                      'https://slack.com/api/chat.postMessage'
-                name: Fetch Slack Handle For Github Handle
+                command: "#!/bin/bash\nset -eo pipefail\nCODA_CIRCLECI_USER_NAME_COL=\"c-6ni4kHGNwE\"\nCODA_CIRCLECI_USER_ALIAS_COL=\"c-26If9Zttyp\"\nUSER_EMAIL=\"\"\nfunction run_main() {\n    USER_ALIAS=$(curl -s -H \"Authorization: Bearer ${CODA_API_TOKEN}\" \\\n    -G --data-urlencode \"query=${CODA_CIRCLECI_USER_NAME_COL}:\\\"${CIRCLE_USERNAME}\\\"\" \\\n    'https://staging.coda.io/apis/v1/docs/s2i6oFeghW/tables/grid-QGyaiXZDwu/rows' \\\n    | jq --arg CODA_CIRCLECI_USER_ALIAS_COL \"$CODA_CIRCLECI_USER_ALIAS_COL\" '.items[0].values.\"$CODA_CIRCLECI_USER_ALIAS_COL\"' | tr -d '\"')\n    if [ \"$USER_ALIAS\" != \"null\" ]; then\n        USER_EMAIL=$([[ \"${USER_ALIAS}\" == *@* ]] && echo \"$USER_ALIAS\" || echo \"${USER_ALIAS}@coda.io\")\n    fi\n    echo \"$USER_EMAIL\"\n    echo \"export USER_EMAIL=${USER_EMAIL}\" >> \"$BASH_ENV\"\n    if [ ! -z \"$SLACK_BOT_TOKEN\" ]; then \n        SLACK_USER_ID=$(curl -s -H \"Authorization: Bearer $SLACK_BOT_TOKEN\" \\\n            https://slack.com/api/users.lookupByEmail?email=${USER_EMAIL} \\\n            | jq '.user.id' | tr -d '\"')\n        echo \"export SLACK_USER_ID=${SLACK_USER_ID}\" >> \"$BASH_ENV\"\n    fi\n}\n\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*$ORB_TEST_ENV}\" == \"$0\" ]; then\n    run_main\nfi"
+                environment:
+                    SLACK_BOT_TOKEN: << parameters.SLACK_BOT_TOKEN >>
+                name: Fetch User Information from Look Up Table
+            - when:
+                condition: $SLACK_USER_ID
+                steps:
+                    - run:
+                        command: |-
+                            set -eo pipefail
+                            curl -X POST -H "Authorization: Bearer << parameters.SLACK_BOT_TOKEN >>" \
+                              -H "Content-Type: application/json" -d \
+                              "{ \
+                                \"channel\": \"${SLACK_USER_ID}\", \
+                                \"attachments\": [ \
+                                  { \
+                                    \"text\": \"Pending Approval for ${CIRCLE_PROJECT_REPONAME} push (${CIRCLE_USERNAME})\", \
+                                    \"fields\": [ \
+                                      { \
+                                        \"title\": \"Project\", \
+                                        \"value\": \"${CIRCLE_PROJECT_REPONAME}\", \
+                                        \"short\": true \
+                                      }, \
+                                      { \
+                                        \"title\": \"Job Number\", \
+                                        \"value\": \"${CIRCLE_BUILD_NUM}\", \
+                                        \"short\": true \
+                                      } \
+                                    ], \
+                                    \"actions\": [ \
+                                      { \
+                                        \"type\": \"button\", \
+                                        \"text\": \"Visit Workflow\", \
+                                        \"url\": \"https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\" \
+                                      } \
+                                    ], \
+                                    \"color\": \"#f46a54\" \
+                                  } \
+                                ] \
+                              }" \
+                              'https://slack.com/api/chat.postMessage'
+                        name: Send Slack Message
 executors:
     default:
         description: |
